### ISSUE TITLE
Feature request: reload from console

### ISSUE THREAD

**Issue by SlimeDog** [Andre601/HelpGUI#10]
# Suggestion
Please allow _**helpgui reload**_ from the console.

## What does it add/change?
It would make debugging and testing configuration changes much easier.

**Comment by Andre601** [comment]
This is difficult to do because of how commands are handled in HelpGUI.
It uses Aikars [ACF (Annotation Command Framework)](https://github.com/aikar/commands) for handling commands, which as of now doesn't support Consoles.

**Comment by SlimeDog** [comment]
Thanks.

**Comment by Andre601** [comment]
Added it in [**2.7.5**](https://www.spigotmc.org/resources/helpgui.33245/update?update=268451)

**Comment by SlimeDog** [comment]
thanks.
